CREATE TABLE `XC_PROXY_IP` (
  `IP` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'IP地址',
  `PORT` INT NOT NULL DEFAULT 80 COMMENT '端口号',
  `REGION` STRING NOT NULL DEFAULT '' COMMENT '地区'
  UNIQUE KEY `IPPORTPERM` (`IP`,`PORT`)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;